theme = "theme_settings"

[editor]
line-number = "relative"
mouse = true
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = false
idle-timeout = 0
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
# esc = ["collapse_selection", "keep_primary_selection", ":w"] # remove additional cursors and selections
y = "yank_joined_to_clipboard" # use my system clipboard
p = ["paste_clipboard_after", ":w"]
P = ["replace_selections_with_clipboard", ":w"] # paste over selection
d = ["yank_joined_to_clipboard", "delete_selection", ":w"] # add deleted text to system clipboaard
x = ["extend_line_below", "select_mode"] # go into select mode when you select line. This lets you undo going to far with x as well as more expected "c" behavour when combined with my select "c" mapping
";" = "flip_selections"
"," = "repeat_last_motion"

[keys.select]
c = ["trim_selections", "change_selection"] # when changing a line this stops the cursor moving to the beginning of the line underneath

[keys.normal.space]
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling files rather than a file tree
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers
"q" = ":q"