theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
true-color = true
undercurl = true
color-modes = true
cursorline = true
auto-save = false
idle-timeout = 0
gutters = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
right = ["diagnostics", "version-control", "position", "file-encoding"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false
git-ignore = false
