tap 'buo/cask-upgrade'
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'nicoverbruggen/homebrew-cask' # For `phpmon`
tap 'teamookla/speedtest' # For `speedtest`

brew 'pkg-config' # bunch of things
brew 'awscli'
brew 'bat'
brew 'c-ares'
brew 'composer'
brew 'coreutils'
brew 'dnsmasq'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'git-delta'
brew 'git-flow'
brew 'git-open'
brew 'git'
brew 'gnu-sed'
brew 'gnu-which'
brew 'gnupg'
brew 'gti'
brew 'java'
brew 'lazygit'
brew 'less'
brew 'mackup'
brew 'mas'
brew 'nginx'
brew 'node'
brew 'php'
brew 'postgresql@13'
brew 'ripgrep'
brew 'speedtest'
brew 'sqlite'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'z'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'zsh'

# apps
cask '1password'
cask 'brave-browser'
cask 'canon-eos-webcam-utility'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'helo'
cask 'imageoptim'
cask 'loom'
cask 'messenger'
cask 'microsoft-teams'
cask 'mimestream'
cask 'notion'
cask 'phpmon'
cask 'ray'
cask 'raycast'
cask 'slack'
cask 'sourcetree'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'telegram'
cask 'the-unarchiver'
cask 'tinkerwell'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
# cask 'warp'
cask 'zoom'

# mas 'Adblock Plus', id: 1432731683
# mas 'GarageBand', id: 682658836
# mas 'iMovie', id: 408981434
# mas 'Keynote', id: 409183694
# mas 'Numbers', id: 409203825
# mas 'Pages', id: 409201541
